# CircleCI Go configrations
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
# 
version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/shirasudon/go-chat

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout

      - run: 
          name: go get
          command: |
            go get -t -d -v ./...

      - run: 
          name: go get test tools
          command: |
            go get github.com/jstemmer/go-junit-report
            go get github.com/haya14busa/goverage

      - run: 
          name: Run static checkers
          command: |
            go vet ./...

      - run: mkdir -p $TEST_RESULTS

      - run:
          name: Run unit tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            go test -v -race ./... | tee ${TEST_RESULTS}/go-test.out
            bash .circleci/coverage.sh

      - run: 
          name: Upload coverage profile to codecov.io
          command: |
            cp ${TEST_RESULTS}/go-test.coverage ./coverage.txt
            bash <(curl -s https://codecov.io/bash)

      - run: 
          name: Build main program
          command: go build -o ./main/build_bin ./main

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results

